### ISSUE TITLE
Remember scroll position upon reload?

### ISSUE THREAD

**Issue by orschiro** [tabernacle8/AutoReloadTab#2]
@tabernacle8 thanks for this great extension!

Is it possible to remember scroll position upon reload?

**Comment by tabernacle8** [comment]
Hi there,

This project was discontinued for a while when you posted this comment but it has since been reinstated. As I work to bring this extension back to the google play store, I'll definitely work to make sure this suggestion gets implemented.

Thanks!

**Comment by tabernacle8** [comment]
Implemented in 1.3.0
